import { Recipe } from "./store";

export const groceryKnowledgeBase: Record<string, { packSize: number, packUnit: string, packName: string }> = {
  'milk': { packSize: 2200, packUnit: 'ml', packName: '4-Pint Milk' },
  'semi-skimmed milk': { packSize: 2200, packUnit: 'ml', packName: '4-Pint Semi-Skimmed Milk' },
  'whole milk': { packSize: 2200, packUnit: 'ml', packName: '4-Pint Whole Milk' },
  'skimmed milk': { packSize: 2200, packUnit: 'ml', packName: '4-Pint Skimmed Milk' },
  'eggs': { packSize: 6, packUnit: 'whole', packName: 'Box of 6 Eggs' },
  'large eggs': { packSize: 6, packUnit: 'whole', packName: 'Box of 6 Large Eggs' },
  'butter': { packSize: 250, packUnit: 'g', packName: 'Block of Butter (250g)' },
  'unsalted butter': { packSize: 250, packUnit: 'g', packName: 'Unsalted Butter (250g)' },
  'cheddar cheese': { packSize: 350, packUnit: 'g', packName: 'Block of Cheddar (350g)' },
  'grated cheddar': { packSize: 250, packUnit: 'g', packName: 'Grated Cheddar (250g)' },
  'mozzarella': { packSize: 125, packUnit: 'g', packName: 'Ball of Mozzarella (125g)' },
  'grated mozzarella': { packSize: 250, packUnit: 'g', packName: 'Grated Mozzarella (250g)' },
  'parmesan': { packSize: 150, packUnit: 'g', packName: 'Wedge of Parmesan (150g)' },
  'cream cheese': { packSize: 200, packUnit: 'g', packName: 'Tub of Cream Cheese (200g)' },
  'double cream': { packSize: 300, packUnit: 'ml', packName: 'Pot of Double Cream (300ml)' },
  'single cream': { packSize: 300, packUnit: 'ml', packName: 'Pot of Single Cream (300ml)' },
  'sour cream': { packSize: 300, packUnit: 'ml', packName: 'Tub of Sour Cream (300ml)' },
  'creme fraiche': { packSize: 300, packUnit: 'ml', packName: 'Tub of Creme Fraiche (300ml)' },
  'natural yogurt': { packSize: 500, packUnit: 'g', packName: 'Pot of Natural Yogurt (500g)' },
  'greek yogurt': { packSize: 500, packUnit: 'g', packName: 'Pot of Greek Yogurt (500g)' },
  'yogurt tubes': { packSize: 9, packUnit: 'pack', packName: 'Pack of Yogurt Tubes (9)' },
  'halloumi': { packSize: 225, packUnit: 'g', packName: 'Block of Halloumi (225g)' },
  'feta': { packSize: 200, packUnit: 'g', packName: 'Block of Feta (200g)' },
  'brie': { packSize: 200, packUnit: 'g', packName: 'Wedge of Brie (200g)' },
  'bread': { packSize: 20, packUnit: 'slices', packName: 'Loaf of Bread' },
  'white bread': { packSize: 20, packUnit: 'slices', packName: 'White Loaf' },
  'wholemeal bread': { packSize: 20, packUnit: 'slices', packName: 'Wholemeal Loaf' },
  'seeded bread': { packSize: 20, packUnit: 'slices', packName: 'Seeded Loaf' },
  'sourdough': { packSize: 1, packUnit: 'loaf', packName: 'Sourdough Loaf' },
  'baguette': { packSize: 1, packUnit: 'whole', packName: 'French Baguette' },
  'rolls': { packSize: 6, packUnit: 'pack', packName: 'Pack of Bread Rolls (6)' },
  'burger buns': { packSize: 4, packUnit: 'pack', packName: 'Pack of Burger Buns (4)' },
  'hot dog buns': { packSize: 6, packUnit: 'pack', packName: 'Pack of Hot Dog Buns (6)' },
  'pita bread': { packSize: 6, packUnit: 'pack', packName: 'Pack of Pita Breads (6)' },
  'naan bread': { packSize: 2, packUnit: 'pack', packName: 'Pack of Naan Breads (2)' },
  'tortilla wraps': { packSize: 8, packUnit: 'pack', packName: 'Pack of Tortilla Wraps (8)' },
  'crumpets': { packSize: 6, packUnit: 'pack', packName: 'Pack of Crumpets (6)' },
  'bagels': { packSize: 5, packUnit: 'pack', packName: 'Pack of Bagels (5)' },
  'croissants': { packSize: 4, packUnit: 'pack', packName: 'Pack of Croissants (4)' },
  'potatoes': { packSize: 1000, packUnit: 'g', packName: 'Bag of Potatoes (1kg)' },
  'baking potatoes': { packSize: 4, packUnit: 'whole', packName: 'Pack of Baking Potatoes (4)' },
  'sweet potatoes': { packSize: 1000, packUnit: 'g', packName: 'Bag of Sweet Potatoes (1kg)' },
  'carrots': { packSize: 500, packUnit: 'g', packName: 'Bag of Carrots (500g)' },
  'onion': { packSize: 3, packUnit: 'whole', packName: 'Net of Onions (3)' },
  'red onion': { packSize: 3, packUnit: 'whole', packName: 'Net of Red Onions (3)' },
  'garlic': { packSize: 3, packUnit: 'bulb', packName: 'Net of Garlic (3 bulbs)' },
  'bell peppers': { packSize: 3, packUnit: 'whole', packName: 'Mixed Peppers (3)' },
  'red pepper': { packSize: 1, packUnit: 'whole', packName: 'Red Pepper' },
  'green pepper': { packSize: 1, packUnit: 'whole', packName: 'Green Pepper' },
  'yellow pepper': { packSize: 1, packUnit: 'whole', packName: 'Yellow Pepper' },
  'mushrooms': { packSize: 300, packUnit: 'g', packName: 'Punnet of Mushrooms (300g)' },
  'chestnut mushrooms': { packSize: 250, packUnit: 'g', packName: 'Punnet of Chestnut Mushrooms (250g)' },
  'tomatoes': { packSize: 6, packUnit: 'whole', packName: 'Pack of Tomatoes (6)' },
  'cherry tomatoes': { packSize: 250, packUnit: 'g', packName: 'Punnet of Cherry Tomatoes (250g)' },
  'cucumber': { packSize: 1, packUnit: 'whole', packName: 'Cucumber' },
  'lettuce': { packSize: 1, packUnit: 'head', packName: 'Iceberg Lettuce' },
  'romaine lettuce': { packSize: 2, packUnit: 'head', packName: 'Twin Pack Romaine Lettuce' },
  'salad leaves': { packSize: 100, packUnit: 'g', packName: 'Bag of Mixed Salad (100g)' },
  'spinach': { packSize: 260, packUnit: 'g', packName: 'Bag of Spinach (260g)' },
  'broccoli': { packSize: 1, packUnit: 'head', packName: 'Head of Broccoli' },
  'cauliflower': { packSize: 1, packUnit: 'head', packName: 'Head of Cauliflower' },
  'cabbage': { packSize: 1, packUnit: 'head', packName: 'White Cabbage' },
  'red cabbage': { packSize: 1, packUnit: 'head', packName: 'Red Cabbage' },
  'brussels sprouts': { packSize: 500, packUnit: 'g', packName: 'Bag of Brussels Sprouts (500g)' },
  'courgette': { packSize: 3, packUnit: 'whole', packName: 'Pack of Courgettes (3)' },
  'aubergine': { packSize: 1, packUnit: 'whole', packName: 'Aubergine' },
  'leeks': { packSize: 500, packUnit: 'g', packName: 'Pack of Leeks (500g)' },
  'celery': { packSize: 1, packUnit: 'bunch', packName: 'Head of Celery' },
  'spring onions': { packSize: 1, packUnit: 'bunch', packName: 'Bunch of Spring Onions' },
  'parsnips': { packSize: 500, packUnit: 'g', packName: 'Bag of Parsnips (500g)' },
  'butternut squash': { packSize: 1, packUnit: 'whole', packName: 'Butternut Squash' },
  'swede': { packSize: 1, packUnit: 'whole', packName: 'Swede' },
  'green beans': { packSize: 200, packUnit: 'g', packName: 'Pack of Green Beans (200g)' },
  'sugar snap peas': { packSize: 150, packUnit: 'g', packName: 'Pack of Sugar Snap Peas (150g)' },
  'asparagus': { packSize: 250, packUnit: 'g', packName: 'Bundle of Asparagus (250g)' },
  'avocado': { packSize: 2, packUnit: 'whole', packName: 'Pack of Avocados (2)' },
  'apples': { packSize: 6, packUnit: 'whole', packName: 'Bag of Apples (6)' },
  'bananas': { packSize: 5, packUnit: 'whole', packName: 'Bunch of Bananas (5)' },
  'oranges': { packSize: 5, packUnit: 'whole', packName: 'Pack of Oranges (5)' },
  'satsumas': { packSize: 600, packUnit: 'g', packName: 'Net of Satsumas (600g)' },
  'grapes': { packSize: 500, packUnit: 'g', packName: 'Punnet of Grapes (500g)' },
  'strawberries': { packSize: 400, packUnit: 'g', packName: 'Punnet of Strawberries (400g)' },
  'raspberries': { packSize: 150, packUnit: 'g', packName: 'Punnet of Raspberries (150g)' },
  'blueberries': { packSize: 150, packUnit: 'g', packName: 'Punnet of Blueberries (150g)' },
  'lemons': { packSize: 4, packUnit: 'whole', packName: 'Pack of Lemons (4)' },
  'limes': { packSize: 4, packUnit: 'whole', packName: 'Pack of Limes (4)' },
  'pears': { packSize: 4, packUnit: 'whole', packName: 'Pack of Pears (4)' },
  'plums': { packSize: 400, packUnit: 'g', packName: 'Punnet of Plums (400g)' },
  'peaches': { packSize: 4, packUnit: 'whole', packName: 'Pack of Peaches (4)' },
  'kiwi': { packSize: 6, packUnit: 'whole', packName: 'Pack of Kiwis (6)' },
  'mango': { packSize: 1, packUnit: 'whole', packName: 'Mango' },
  'pineapple': { packSize: 1, packUnit: 'whole', packName: 'Pineapple' },
  'melon': { packSize: 1, packUnit: 'whole', packName: 'Cantaloupe Melon' },
  'chicken breast': { packSize: 500, packUnit: 'g', packName: 'Chicken Breasts (500g)' },
  'chicken thighs': { packSize: 500, packUnit: 'g', packName: 'Chicken Thighs (500g)' },
  'whole chicken': { packSize: 1, packUnit: 'whole', packName: 'Whole Chicken (Medium)' },
  'chicken wings': { packSize: 1000, packUnit: 'g', packName: 'Chicken Wings (1kg)' },
  'minced beef': { packSize: 500, packUnit: 'g', packName: 'Beef Mince (500g)' },
  'beef mince': { packSize: 500, packUnit: 'g', packName: 'Beef Mince (500g)' },
  'beef steak': { packSize: 2, packUnit: 'steak', packName: 'Rump Steaks (2 pack)' },
  'diced beef': { packSize: 500, packUnit: 'g', packName: 'Diced Beef (500g)' },
  'pork sausages': { packSize: 8, packUnit: 'pack', packName: 'Pack of Pork Sausages (8)' },
  'bacon': { packSize: 300, packUnit: 'g', packName: 'Pack of Bacon (300g)' },
  'pork chops': { packSize: 4, packUnit: 'chop', packName: 'Pork Chops (4 pack)' },
  'minced pork': { packSize: 500, packUnit: 'g', packName: 'Pork Mince (500g)' },
  'lamb chops': { packSize: 4, packUnit: 'chop', packName: 'Lamb Chops (4 pack)' },
  'minced lamb': { packSize: 500, packUnit: 'g', packName: 'Lamb Mince (500g)' },
  'cooked ham': { packSize: 120, packUnit: 'g', packName: 'Pack of Cooked Ham (120g)' },
  'salami': { packSize: 100, packUnit: 'g', packName: 'Pack of Salami (100g)' },
  'chorizo': { packSize: 200, packUnit: 'g', packName: 'Chorizo Ring (200g)' },
  'salmon fillets': { packSize: 2, packUnit: 'fillet', packName: 'Salmon Fillets (2 pack)' },
  'white fish fillets': { packSize: 2, packUnit: 'fillet', packName: 'White Fish Fillets (2 pack)' },
  'cod fillets': { packSize: 2, packUnit: 'fillet', packName: 'Cod Fillets (2 pack)' },
  'smoked salmon': { packSize: 100, packUnit: 'g', packName: 'Smoked Salmon (100g)' },
  'prawns': { packSize: 150, packUnit: 'g', packName: 'King Prawns (150g)' },
  'tinned tuna': { packSize: 4, packUnit: 'tin', packName: 'Tinned Tuna (4 pack)' },
  'spaghetti': { packSize: 500, packUnit: 'g', packName: 'Spaghetti Pasta (500g)' },
  'macaroni': { packSize: 500, packUnit: 'g', packName: 'Macaroni Pasta (500g)' },
  'penne': { packSize: 500, packUnit: 'g', packName: 'Penne Pasta (500g)' },
  'fusilli': { packSize: 500, packUnit: 'g', packName: 'Fusilli Pasta (500g)' },
  'lasagne sheets': { packSize: 500, packUnit: 'g', packName: 'Lasagne Sheets (500g)' },
  'egg noodles': { packSize: 250, packUnit: 'g', packName: 'Egg Noodles (250g)' },
  'rice noodles': { packSize: 200, packUnit: 'g', packName: 'Rice Noodles (200g)' },
  'basmati rice': { packSize: 1000, packUnit: 'g', packName: 'Basmati Rice (1kg)' },
  'long grain rice': { packSize: 1000, packUnit: 'g', packName: 'Long Grain Rice (1kg)' },
  'brown rice': { packSize: 1000, packUnit: 'g', packName: 'Brown Rice (1kg)' },
  'arborio rice': { packSize: 500, packUnit: 'g', packName: 'Risotto Rice (500g)' },
  'plain flour': { packSize: 1000, packUnit: 'g', packName: 'Plain Flour (1kg)' },
  'self raising flour': { packSize: 1000, packUnit: 'g', packName: 'Self-Raising Flour (1kg)' },
  'caster sugar': { packSize: 1000, packUnit: 'g', packName: 'Caster Sugar (1kg)' },
  'granulated sugar': { packSize: 1000, packUnit: 'g', packName: 'Granulated Sugar (1kg)' },
  'brown sugar': { packSize: 500, packUnit: 'g', packName: 'Brown Sugar (500g)' },
  'icing sugar': { packSize: 500, packUnit: 'g', packName: 'Icing Sugar (500g)' },
  'porridge oats': { packSize: 1000, packUnit: 'g', packName: 'Porridge Oats (1kg)' },
  'cereal': { packSize: 500, packUnit: 'g', packName: 'Box of Cereal (500g)' },
  'olive oil': { packSize: 500, packUnit: 'ml', packName: 'Olive Oil (500ml)' },
  'vegetable oil': { packSize: 1000, packUnit: 'ml', packName: 'Vegetable Oil (1L)' },
  'sunflower oil': { packSize: 1000, packUnit: 'ml', packName: 'Sunflower Oil (1L)' },
  'sesame oil': { packSize: 150, packUnit: 'ml', packName: 'Sesame Oil (150ml)' },
  'balsamic vinegar': { packSize: 250, packUnit: 'ml', packName: 'Balsamic Vinegar (250ml)' },
  'white wine vinegar': { packSize: 500, packUnit: 'ml', packName: 'White Wine Vinegar (500ml)' },
  'soy sauce': { packSize: 150, packUnit: 'ml', packName: 'Soy Sauce (150ml)' },
  'ketchup': { packSize: 500, packUnit: 'g', packName: 'Tomato Ketchup (500g)' },
  'mayonnaise': { packSize: 400, packUnit: 'g', packName: 'Mayonnaise (400g)' },
  'mustard': { packSize: 200, packUnit: 'g', packName: 'Mustard (200g)' },
  'honey': { packSize: 340, packUnit: 'g', packName: 'Honey (340g)' },
  'jam': { packSize: 400, packUnit: 'g', packName: 'Strawberry Jam (400g)' },
  'peanut butter': { packSize: 340, packUnit: 'g', packName: 'Peanut Butter (340g)' },
  'marmite': { packSize: 250, packUnit: 'g', packName: 'Marmite (250g)' },
  'pasta sauce': { packSize: 400, packUnit: 'g', packName: 'Pasta Sauce Jar (400g)' },
  'curry sauce': { packSize: 400, packUnit: 'g', packName: 'Curry Sauce Jar (400g)' },
  'baked beans': { packSize: 4, packUnit: 'tin', packName: 'Baked Beans (4 pack)' },
  'chopped tomatoes': { packSize: 4, packUnit: 'tin', packName: 'Chopped Tomatoes (4 pack)' },
  'kidney beans': { packSize: 400, packUnit: 'g', packName: 'Kidney Beans (400g tin)' },
  'chickpeas': { packSize: 400, packUnit: 'g', packName: 'Chickpeas (400g tin)' },
  'sweetcorn': { packSize: 3, packUnit: 'tin', packName: 'Sweetcorn (3 pack)' },
  'coconut milk': { packSize: 400, packUnit: 'ml', packName: 'Coconut Milk (400ml tin)' },
  'chicken stock': { packSize: 12, packUnit: 'cube', packName: 'Chicken Stock Cubes (12)' },
  'beef stock': { packSize: 12, packUnit: 'cube', packName: 'Beef Stock Cubes (12)' },
  'vegetable stock': { packSize: 12, packUnit: 'cube', packName: 'Vegetable Stock Cubes (12)' },
  'crisps': { packSize: 6, packUnit: 'pack', packName: 'Multipack Crisps (6)' },
  'biscuits': { packSize: 1, packUnit: 'pack', packName: 'Pack of Biscuits' },
  'chocolate': { packSize: 100, packUnit: 'g', packName: 'Chocolate Bar (100g)' },
  'tea bags': { packSize: 80, packUnit: 'bag', packName: 'Box of Tea Bags (80)' },
  'coffee': { packSize: 200, packUnit: 'g', packName: 'Instant Coffee (200g)' },
  'squash': { packSize: 1000, packUnit: 'ml', packName: 'Fruit Squash (1L)' },
  'fruit juice': { packSize: 1000, packUnit: 'ml', packName: 'Fruit Juice (1L)' },
  'frozen peas': { packSize: 1000, packUnit: 'g', packName: 'Frozen Peas (1kg)' },
  'frozen chips': { packSize: 1500, packUnit: 'g', packName: 'Frozen Chips (1.5kg)' },
  'ice cream': { packSize: 900, packUnit: 'ml', packName: 'Tub of Ice Cream (900ml)' },
};

const calc = (qty: number) => ({
  quantity: qty,
  adultQty: Math.round((qty / 3) * 10) / 10,
  childQty: Math.round(((qty / 3) * 0.5) * 10) / 10
});

export const defaultRecipes: Recipe[] = [
  { id: 'r0', name: 'Spaghetti Bolognese', ingredients: [{ id: 'r0_i0', name: 'Minced Beef', ...calc(500), unit: 'g' }, { id: 'r0_i1', name: 'Spaghetti', ...calc(400), unit: 'g' }, { id: 'r0_i2', name: 'Pasta Sauce', ...calc(1), unit: 'jar' }, { id: 'r0_i3', name: 'Onion', ...calc(1), unit: 'whole' }, { id: 'r0_i4', name: 'Mushrooms', ...calc(200), unit: 'g' }] },
  { id: 'r1', name: 'Chicken Fajitas', ingredients: [{ id: 'r1_i0', name: 'Chicken Breast', ...calc(500), unit: 'g' }, { id: 'r1_i1', name: 'Fajita Kit', ...calc(1), unit: 'pack' }, { id: 'r1_i2', name: 'Bell Peppers', ...calc(2), unit: 'whole' }, { id: 'r1_i3', name: 'Onion', ...calc(1), unit: 'whole' }, { id: 'r1_i4', name: 'Sour Cream', ...calc(1), unit: 'tub' }] },
  { id: 'r2', name: 'Sausage and Mash', ingredients: [{ id: 'r2_i0', name: 'Pork Sausages', ...calc(8), unit: 'pack' }, { id: 'r2_i1', name: 'Potatoes', ...calc(1000), unit: 'g' }, { id: 'r2_i2', name: 'Gravy Granules', ...calc(1), unit: 'tub' }, { id: 'r2_i3', name: 'Frozen Peas', ...calc(300), unit: 'g' }] },
  { id: 'r3', name: 'Fish Pie', ingredients: [{ id: 'r3_i0', name: 'Fish Pie Mix', ...calc(400), unit: 'g' }, { id: 'r3_i1', name: 'Potatoes', ...calc(800), unit: 'g' }, { id: 'r3_i2', name: 'Milk', ...calc(500), unit: 'ml' }, { id: 'r3_i3', name: 'Butter', ...calc(50), unit: 'g' }, { id: 'r3_i4', name: 'Cheddar Cheese', ...calc(100), unit: 'g' }] },
  { id: 'r4', name: 'Vegetable Stir Fry', ingredients: [{ id: 'r4_i0', name: 'Stir Fry Veg', ...calc(1), unit: 'pack' }, { id: 'r4_i1', name: 'Egg Noodles', ...calc(2), unit: 'pack' }, { id: 'r4_i2', name: 'Soy Sauce', ...calc(1), unit: 'bottle' }, { id: 'r4_i3', name: 'Tofu', ...calc(1), unit: 'pack' }, { id: 'r4_i4', name: 'Sweet Chilli Sauce', ...calc(1), unit: 'bottle' }] },
  { id: 'r5', name: 'Macaroni Cheese', ingredients: [{ id: 'r5_i0', name: 'Macaroni', ...calc(400), unit: 'g' }, { id: 'r5_i1', name: 'Cheddar Cheese', ...calc(300), unit: 'g' }, { id: 'r5_i2', name: 'Milk', ...calc(500), unit: 'ml' }, { id: 'r5_i3', name: 'Butter', ...calc(50), unit: 'g' }, { id: 'r5_i4', name: 'Plain Flour', ...calc(50), unit: 'g' }] },
  { id: 'r6', name: 'Cottage Pie', ingredients: [{ id: 'r6_i0', name: 'Minced Beef', ...calc(500), unit: 'g' }, { id: 'r6_i1', name: 'Potatoes', ...calc(1000), unit: 'g' }, { id: 'r6_i2', name: 'Carrots', ...calc(2), unit: 'whole' }, { id: 'r6_i3', name: 'Beef Stock', ...calc(1), unit: 'cube' }] },
  { id: 'r7', name: 'Chicken Curry', ingredients: [{ id: 'r7_i0', name: 'Chicken Breast', ...calc(500), unit: 'g' }, { id: 'r7_i1', name: 'Curry Sauce', ...calc(1), unit: 'jar' }, { id: 'r7_i2', name: 'Basmati Rice', ...calc(300), unit: 'g' }, { id: 'r7_i3', name: 'Naan Bread', ...calc(2), unit: 'pack' }] },
  { id: 'r8', name: 'Tuna Pasta Bake', ingredients: [{ id: 'r8_i0', name: 'Penne', ...calc(400), unit: 'g' }, { id: 'r8_i1', name: 'Tinned Tuna', ...calc(2), unit: 'tins' }, { id: 'r8_i2', name: 'Pasta Bake Sauce', ...calc(1), unit: 'jar' }, { id: 'r8_i3', name: 'Cheddar Cheese', ...calc(150), unit: 'g' }] },
  { id: 'r9', name: 'Beef Burgers', ingredients: [{ id: 'r9_i0', name: 'Beef Burgers', ...calc(4), unit: 'pack' }, { id: 'r9_i1', name: 'Burger Buns', ...calc(4), unit: 'pack' }, { id: 'r9_i2', name: 'Lettuce', ...calc(1), unit: 'head' }, { id: 'r9_i3', name: 'Tomatoes', ...calc(2), unit: 'whole' }] },
  { id: 'r10', name: 'Roast Chicken', ingredients: [{ id: 'r10_i0', name: 'Whole Chicken', ...calc(1), unit: 'whole' }, { id: 'r10_i1', name: 'Potatoes', ...calc(1000), unit: 'g' }, { id: 'r10_i2', name: 'Carrots', ...calc(500), unit: 'g' }, { id: 'r10_i3', name: 'Broccoli', ...calc(1), unit: 'head' }, { id: 'r10_i4', name: 'Gravy Granules', ...calc(1), unit: 'tub' }] },
  { id: 'r11', name: 'Chilli Con Carne', ingredients: [{ id: 'r11_i0', name: 'Minced Beef', ...calc(500), unit: 'g' }, { id: 'r11_i1', name: 'Kidney Beans', ...calc(400), unit: 'g' }, { id: 'r11_i2', name: 'Chopped Tomatoes', ...calc(400), unit: 'g' }, { id: 'r11_i3', name: 'Onion', ...calc(1), unit: 'whole' }, { id: 'r11_i4', name: 'Basmati Rice', ...calc(300), unit: 'g' }] },
  { id: 'r12', name: 'Pesto Pasta', ingredients: [{ id: 'r12_i0', name: 'Penne', ...calc(400), unit: 'g' }, { id: 'r12_i1', name: 'Pesto', ...calc(1), unit: 'jar' }, { id: 'r12_i2', name: 'Cherry Tomatoes', ...calc(250), unit: 'g' }, { id: 'r12_i3', name: 'Parmesan', ...calc(50), unit: 'g' }] },
  { id: 'r13', name: 'Toad in the Hole', ingredients: [{ id: 'r13_i0', name: 'Pork Sausages', ...calc(8), unit: 'pack' }, { id: 'r13_i1', name: 'Plain Flour', ...calc(150), unit: 'g' }, { id: 'r13_i2', name: 'Eggs', ...calc(2), unit: 'whole' }, { id: 'r13_i3', name: 'Milk', ...calc(200), unit: 'ml' }] },
  { id: 'r14', name: 'Chicken Caesar Salad', ingredients: [{ id: 'r14_i0', name: 'Chicken Breast', ...calc(400), unit: 'g' }, { id: 'r14_i1', name: 'Romaine Lettuce', ...calc(1), unit: 'head' }, { id: 'r14_i2', name: 'Caesar Dressing', ...calc(1), unit: 'bottle' }, { id: 'r14_i3', name: 'Croutons', ...calc(1), unit: 'pack' }, { id: 'r14_i4', name: 'Parmesan', ...calc(50), unit: 'g' }] },
  { id: 'r15', name: 'Lasagne', ingredients: [{ id: 'r15_i0', name: 'Minced Beef', ...calc(500), unit: 'g' }, { id: 'r15_i1', name: 'Lasagne Sheets', ...calc(10), unit: 'sheets' }, { id: 'r15_i2', name: 'Pasta Sauce', ...calc(1), unit: 'jar' }, { id: 'r15_i3', name: 'White Sauce', ...calc(1), unit: 'jar' }, { id: 'r15_i4', name: 'Cheddar Cheese', ...calc(150), unit: 'g' }] },
  { id: 'r16', name: 'Shepherds Pie', ingredients: [{ id: 'r16_i0', name: 'Minced Lamb', ...calc(500), unit: 'g' }, { id: 'r16_i1', name: 'Potatoes', ...calc(1000), unit: 'g' }, { id: 'r16_i2', name: 'Carrots', ...calc(2), unit: 'whole' }, { id: 'r16_i3', name: 'Onion', ...calc(1), unit: 'whole' }, { id: 'r16_i4', name: 'Lamb Stock', ...calc(1), unit: 'cube' }] },
  { id: 'r17', name: 'Prawn Stir Fry', ingredients: [{ id: 'r17_i0', name: 'Prawns', ...calc(200), unit: 'g' }, { id: 'r17_i1', name: 'Stir Fry Veg', ...calc(1), unit: 'pack' }, { id: 'r17_i2', name: 'Rice Noodles', ...calc(200), unit: 'g' }, { id: 'r17_i3', name: 'Soy Sauce', ...calc(1), unit: 'bottle' }] },
  { id: 'r18', name: 'Sweet and Sour Pork', ingredients: [{ id: 'r18_i0', name: 'Diced Pork', ...calc(500), unit: 'g' }, { id: 'r18_i1', name: 'Sweet and Sour Sauce', ...calc(1), unit: 'jar' }, { id: 'r18_i2', name: 'Bell Peppers', ...calc(2), unit: 'whole' }, { id: 'r18_i3', name: 'Pineapple', ...calc(1), unit: 'tin' }, { id: 'r18_i4', name: 'Basmati Rice', ...calc(300), unit: 'g' }] },
  { id: 'r19', name: 'Chicken and Mushroom Pie', ingredients: [{ id: 'r19_i0', name: 'Chicken Breast', ...calc(500), unit: 'g' }, { id: 'r19_i1', name: 'Mushrooms', ...calc(250), unit: 'g' }, { id: 'r19_i2', name: 'Puff Pastry', ...calc(1), unit: 'pack' }, { id: 'r19_i3', name: 'Chicken Stock', ...calc(1), unit: 'cube' }] },
  { id: 'r20', name: 'Vegetable Curry', ingredients: [{ id: 'r20_i0', name: 'Sweet Potatoes', ...calc(500), unit: 'g' }, { id: 'r20_i1', name: 'Cauliflower', ...calc(1), unit: 'head' }, { id: 'r20_i2', name: 'Curry Sauce', ...calc(1), unit: 'jar' }, { id: 'r20_i3', name: 'Basmati Rice', ...calc(300), unit: 'g' }] },
  { id: 'r21', name: 'Bangers and Mash', ingredients: [{ id: 'r21_i0', name: 'Pork Sausages', ...calc(8), unit: 'pack' }, { id: 'r21_i1', name: 'Potatoes', ...calc(1000), unit: 'g' }, { id: 'r21_i2', name: 'Onion', ...calc(2), unit: 'whole' }, { id: 'r21_i3', name: 'Beef Stock', ...calc(1), unit: 'cube' }] },
  { id: 'r22', name: 'Fish and Chips', ingredients: [{ id: 'r22_i0', name: 'White Fish Fillets', ...calc(4), unit: 'fillet' }, { id: 'r22_i1', name: 'Potatoes', ...calc(1000), unit: 'g' }, { id: 'r22_i2', name: 'Frozen Peas', ...calc(300), unit: 'g' }, { id: 'r22_i3', name: 'Tartare Sauce', ...calc(1), unit: 'jar' }] },
  { id: 'r23', name: 'Pork Chops and Apples', ingredients: [{ id: 'r23_i0', name: 'Pork Chops', ...calc(4), unit: 'chop' }, { id: 'r23_i1', name: 'Apples', ...calc(2), unit: 'whole' }, { id: 'r23_i2', name: 'Potatoes', ...calc(800), unit: 'g' }, { id: 'r23_i3', name: 'Green Beans', ...calc(200), unit: 'g' }] },
  { id: 'r24', name: 'Beef Stew', ingredients: [{ id: 'r24_i0', name: 'Diced Beef', ...calc(500), unit: 'g' }, { id: 'r24_i1', name: 'Potatoes', ...calc(500), unit: 'g' }, { id: 'r24_i2', name: 'Carrots', ...calc(3), unit: 'whole' }, { id: 'r24_i3', name: 'Onion', ...calc(1), unit: 'whole' }, { id: 'r24_i4', name: 'Beef Stock', ...calc(2), unit: 'cube' }] },
];

export const defaultBundles: Recipe[] = [
  { id: 'b1', name: 'Standard Kids Lunchbox', ingredients: [{ id: 'bi1', name: 'Ham', quantity: 1, unit: 'pack' }, { id: 'bi2', name: 'Bread', quantity: 1, unit: 'loaf' }, { id: 'bi3', name: 'Apples', quantity: 5, unit: 'whole' }, { id: 'bi4', name: 'Yogurt Tubes', quantity: 1, unit: 'pack' }] },
  { id: 'b2', name: 'Weekend Fry Up', ingredients: [{ id: 'bi5', name: 'Eggs', quantity: 6, unit: 'whole' }, { id: 'bi6', name: 'Bacon', quantity: 1, unit: 'pack' }, { id: 'bi7', name: 'Baked Beans', quantity: 1, unit: 'tin' }] },
];
